name: Release

on:
  push:
    tags:
      - 'v*'

permissions: {}
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: run release script
        run: pnpm run release ${{ steps.get_version.outputs.version-without-v }}
